# Install python dependencies
- block:
  - name: Install neovim python dependencies
    apt: name={{ item }} state=installed
    with_items:
      - "{{ boss__vim_python_required_packages }}"

  become: true
  become_user: root
  tags:
    - bootstrap
    - install
    - update

# Install ycm dependencies
- block:
  - name: Install you complete me dependencies
    apt: name={{ item }} state=installed
    with_items:
      - "{{ boss__vim_ycm_packages }}"

  become: true
  become_user: root
  tags:
    - bootstrap
    - install
    - update

# Install neovim
- block:
    - name: Add neovim ppa
      apt_repository: repo="{{ boss__vim_neovim_ppa }}" state=present
      when: ansible_os_family == "Debian"

    - name: Install neovim from ppa
      apt: name="{{ boss__vim_neovim_name }}" state="{{ install_state }}"

    - name: use nvim for vi
      alternatives: name=vi path=/usr/bin/nvim
    - name: use nvim for vim
      alternatives: name=vim path=/usr/bin/nvim
    - name: use nvim for editor
      alternatives: name=editor path=/usr/bin/nvim


  become: true
  become_user: root

  tags:
    - bootstrap
    - install
    - update

- block:
    - name: Install python neovim plugin
      pip:
        name: neovim
        executable: "{{ boss__vim_pip3_name }}"
        state: "{{ boss__vim_install_state }}"
        extra_args: --user

  tags:
    - bootstrap
    - install
    - update

# Install vim-plug
- block:
    - name: Make "{{ boss__vim_neovim_config_dir }}/autoload" directory
      file: path="{{ boss__vim_neovim_config_dir }}/autoload" state=directory

    - name: Install vim-plug
      get_url:
        url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
        dest: "{{ boss__vim_neovim_config_dir }}/autoload/plug.vim"
        force: yes
  tags:
    - bootstrap
    - configure

- block:
    - name: Install vim plugins
      command: nvim "+silent! PlugInstall!" +qall!
      tags: plugins
  tags:
    - bootstrap
    - configure
    - update
